name: Shrani GTFS JSON

on:
  # Sproži se ročno preko GitHub vmesnika
  workflow_dispatch: 
  # Odkomentiraj spodnje vrstice za avtomatsko osveževanje (npr. vsak dan ob 3:00 zjutraj)
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v4

      - name: Priprava Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prenos in razširitev GTFS ZIP datoteke
        run: |
          mkdir -p gtfs
          # Uporabljen je tvoj pravi vir za IJPP GTFS
          curl -L -o gtfs/data.zip "http://gtfs.derp.si/ijpp_gtfs.zip"
          cd gtfs
          unzip data.zip
          # Pobrišemo zip, da sprostimo prostor
          rm data.zip 

      - name: Poženi JS skripto
        run: node process_gtfs.js

      - name: Commit in Push ustvarjenega JSON-a
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stop_to_routes.json
          
          # Če je prišlo do sprememb v podatkih, naredi commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Posodobitev stop_to_routes.json iz IJPP" && git push)
